//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResolverCompiler.Generator {
    using System.Collections.Generic;
    using System;
    
    
    public partial class ResolverTemplate : ResolverTemplateBase {
        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            this.Write(@"// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY STDIC(Static tree DIContainer). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618 // CS0618
#pragma warning disable 612 // CS0612
#pragma warning disable 414 // CS0414
#pragma warning disable 168 // CS0168

#pragma warning disable SA1649
#pragma warning disable SA1312
#pragma warning disable SA1200

namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture( Namespace ));
            this.Write("\n{\n    public class ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ResolverName ));
            this.Write(" : global::STDIC.IResolver\n    {        \n        public global::System.Collection" +
                    "s.Generic.IEnumerable<global::System.Type> HasInjectConstructorTypes =>\n        " +
                    "    ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ResolverName ));
            this.Write(@"GetConstructorHelper.Keys;

        public global::STDIC.IConstructor<T> GetConstructor<T>()
        {
            return ConstructorCache<T>.Constructor;
        }

        private static class ConstructorCache<T>
        {
            public static readonly global::STDIC.IConstructor<T> Constructor;

            static ConstructorCache()
            {
                Constructor = (global::STDIC.IConstructor<T>)");
            this.Write(this.ToStringHelper.ToStringWithCulture( ResolverName ));
            this.Write("GetConstructorHelper.GetConstructor(typeof(T));\n            }\n        }\n    }\n\n  " +
                    "  internal static class ");
            this.Write(this.ToStringHelper.ToStringWithCulture( ResolverName ));
            this.Write("GetConstructorHelper\n    {\n        private static readonly global::System.Collect" +
                    "ions.Generic.Dictionary<global::System.Type, int>\n            ConstructorMap = n" +
                    "ew global::System.Collections.Generic.Dictionary<global::System.Type, int>()\n   " +
                    "         {\n");

    for (var i = 0; i < ConstructorInfos.Length; i++)
    {
        var constructorInfo = ConstructorInfos[i];

            this.Write("                // ");
            this.Write(this.ToStringHelper.ToStringWithCulture( constructorInfo.FullName ));
            this.Write("\n                { typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture( constructorInfo.FullName ));
            this.Write("), ");
            this.Write(this.ToStringHelper.ToStringWithCulture( i ));
            this.Write(" },\n");

    }

            this.Write(@"            };

        internal static global::System.Collections.Generic.IEnumerable<global::System.Type> Keys => ConstructorMap.Keys;

        internal static global::STDIC.IConstructor GetConstructor(global::System.Type t)
        {
            if (!ConstructorMap.TryGetValue(t, out var index)) return null;
            return index switch
            {
");

    for (var i = 0; i < ConstructorInfos.Length; i++)
    {
        var constructorInfo = ConstructorInfos[i];

            this.Write("                ");
            this.Write(this.ToStringHelper.ToStringWithCulture( i ));
            this.Write(" => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture( constructorInfo.ConstructorName ));
            this.Write("(),\n");

    }

            this.Write(@"                _ => null
            };
        }
    }
}

#pragma warning restore 618 // CS0618
#pragma warning restore 612 // CS0612
#pragma warning restore 414 // CS0414
#pragma warning restore 168 // CS0168

#pragma warning restore SA1649
#pragma warning restore SA1312
#pragma warning restore SA1200");
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
        }
    }
    
    public class ResolverTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
