import 'lanes.rb'

skip_docs # skip generate fastlane README.md

before_all do |lane, options|
  set_parameters(lane_context, options, GENERATOR_PARAMS)
  set_parameters(lane_context, options, GENERATOR_BUILD_PARAMS)
  set_parameters(lane_context, options, UNITY_BUILD_PARAMS)
  FastlaneCore::PrintTable.print_values(config: lane_context, hide_keys: [], title: "Build Configuration")
end

error do |lane, exception, options|
  if is_ci?
    p "error #{lane}: #{exception}"
  end
end

after_all do |lane, options|

end

desc "[STDIC ResolverGenerator] Release STDIC"
lane :release_stdic do |options|
  lane_release_stdic(lane_context)
end